spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development, 'validate' or 'none' for production
    show-sql: true # Set to 'true' to log SQL queries, 'false' to disable
    database-platform: org.hibernate.dialect.MySQL8Dialect # Change this if you use another version of MySQL


# Customize server settings if needed
server:
  port: 9001
